name: carist
description: Carist
version: 1.3.0+78623876

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  google_fonts: ^4.0.3
  http: ^0.13.4
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.2
  firebase_crashlytics: ^3.0.15
  firebase_performance: ^0.9.0+14
  cloud_firestore: ^4.4.3
  get: ^4.6.5
  intl: ^0.18.0
  transparent_image: ^2.0.0
  screenshot: ^1.2.3
  share_plus: ^6.3.1
  path_provider: ^2.0.10
  package_info_plus: ^3.0.3
  google_mobile_ads: ^2.3.0
  url_launcher: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
