name: carist
description: Carist
version: 1.1.0+33294703

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  google_fonts: ^2.1.0
  http: ^0.13.3
  firebase_core: ^1.6.0
  firebase_crashlytics: ^2.2.1
  firebase_performance: ^0.7.1+1
  cloud_firestore: ^2.5.1
  get: ^4.3.3
  intl: ^0.17.0
  transparent_image: ^2.0.0
  screenshot: ^1.2.3
  share_plus: ^2.1.4
  path_provider: ^2.0.2
  package_info_plus: ^1.0.4
  google_mobile_ads: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
