name: carist
description: Carist
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  google_fonts: ^1.1.1
  http: ^0.12.2
  firebase_core: ^0.5.3
  cloud_firestore: ^0.14.4
  get: ^4.1.4
  intl: ^0.17.0
  transparent_image: ^2.0.0
  screenshot: ^1.2.3
  share: ^2.0.4
  path_provider: ^2.0.2
  package_info: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/