name: carist
description: Carist
version: 1.2.1+41202541

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  google_fonts: ^2.2.0
  http: ^0.13.4
  firebase_core: ^1.10.6
  firebase_auth: ^3.3.4
  firebase_crashlytics: ^2.4.4
  firebase_performance: ^0.8.0+3
  cloud_firestore: ^3.1.5
  get: ^4.6.1
  intl: ^0.17.0
  transparent_image: ^2.0.0
  screenshot: ^1.2.3
  share_plus: ^3.0.4
  path_provider: ^2.0.10
  package_info_plus: ^1.3.0
  google_mobile_ads: ^1.0.1
  url_launcher: ^6.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
