name: carist
description: Carist
version: 1.3.2+2025052210

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  google_fonts: ^6.2.1
  http: ^1.0.0
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  firebase_crashlytics: ^4.1.0
  firebase_performance: ^0.10.0+5
  cloud_firestore: ^5.4.0
  get: ^4.6.5
  intl: ^0.20.2
  transparent_image: ^2.0.0
  screenshot: ^3.0.0
  share_plus: ^10.0.0
  path_provider: ^2.0.10
  package_info_plus: ^8.0.2
  google_mobile_ads: ^5.2.0
  url_launcher: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
