# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:android)

platform :android do
  desc "Firebase App Distribution"
  lane :firebase do
    sh(command: "flutter build appbundle")
    firebase_app_distribution(
      app: "1:991042250438:android:76aa2288746adf589019c7",
      release_notes: "Fixes and updates",
      android_artifact_path: "./build/app/outputs/bundle/release/app-release.aab"
    )
  end

  desc "Google Play Store - Beta track"
  lane :beta do
    sh(command: "flutter build appbundle")
    upload_to_play_store(
      track: 'beta',
      aab: "./build/app/outputs/bundle/release/app-release.aab"
    )
  end
end

platform :ios do
  desc "Firebase App Distribution"
  lane :firebase do
    get_certificates
    get_provisioning_profile
    build_app
    firebase_app_distribution(
      app: "1:991042250438:ios:0a662d30b970fd849019c7"
    )
  end
end

lane :bump_major do
  flutter_version_manager(
    arguments: "-major",
    yml: "./version.yml",
    pubspec: "./pubspec.yaml")
end

lane :bump_minor do
  flutter_version_manager(
    arguments: "-minor",
    yml: "./version.yml",
    pubspec: "./pubspec.yaml")
end

lane :bump_patch do
  flutter_version_manager(
    arguments: "-patch",
    yml: "./version.yml",
    pubspec: "./pubspec.yaml")
end