# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Submit a new build to Firebase App Distribution"
  lane :beta do
    get_certificates
    get_provisioning_profile
    build_app

    firebase_app_distribution(
      app: "1:991042250438:ios:0a662d30b970fd849019c7"
    )
  end
end